//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mono.Samples.SkeletonApp
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int red = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020001
			public const int semi_black = 2130837505;
			
			// aapt resource value: 0x7f020000
			public const int violet = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int back = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int clear = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int editor = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int image = 2131165186;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int skeleton_activity = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int back = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int clear = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int main_label = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int skeleton_app = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ActionButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TextAppearance = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int TextAppearance_ActionButton = 2131099650;
			
			private Style()
			{
			}
		}
	}
}
