//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mono.Samples.Snake
{
	
	
	public partial class Resource
	{
		
		public class attr
		{
			
			// aapt resource value: 0x7f010000
			public const int tileSize = 2130771968;
			
			private attr()
			{
			}
		}
		
		public class drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int greenstar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int redstar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int yellowstar = 2130837506;
			
			private drawable()
			{
			}
		}
		
		public class layout
		{
			
			// aapt resource value: 0x7f030000
			public const int snake_layout = 2130903040;
			
			private layout()
			{
			}
		}
		
		public class @string
		{
			
			// aapt resource value: 0x7f040000
			public const int mode_ready = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int mode_pause = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int mode_lose_prefix = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int mode_lose_suffix = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int snake_layout_text_text = 2130968580;
			
			private @string()
			{
			}
		}
		
		public class id
		{
			
			// aapt resource value: 0x7f050000
			public const int snake_layout = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int snake = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int text = 2131034114;
			
			private id()
			{
			}
		}
	}
}
