#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Mono.Samples.Snake.Resource", IsApplication=true)]

namespace Mono.Samples.Snake
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int tileSize = 2130771968;
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int greenstar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int redstar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int yellowstar = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int snake = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int snake_layout = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int text = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int snake_layout = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int mode_lose_prefix = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int mode_lose_suffix = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int mode_pause = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int mode_ready = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int snake_layout_text_text = 2130968580;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TileView = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int TileView_tileSize = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
