// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace com.example.monodroid.hcgallery
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int listDragShadowBackground = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int menuIconCamera = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int menuIconShare = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int menuIconToggle = 2130771970;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int actionbar_background_dark = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int actionbar_background_light = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int drag_active_color = 2130968578;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int titles_size = 2131034112;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int big_droid = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_balloon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blue_bike = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_notification_ic_example = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_notification_ic_example_default = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_notification_ic_example_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int chrome_wheel = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cupcake = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int donut = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int eclair = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int froyo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int green_balloon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_camera_holo_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_menu_camera_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_share_holo_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_menu_share_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_menu_toggle_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_menu_toggle_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_stat_notify_example = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int logo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int notification_default_largeicon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int picture_frame = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int picture_frame_default = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int picture_frame_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int picture_frame_selected = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int punk_droid = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int rainbow_bike = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int red_balloon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int stargazer_droid = 2130837533;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int camera = 2131296266;
			
			// aapt resource value: 0x7f090000
			public const int camera_frag = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int frag_content = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int frag_title = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int frags = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int image = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int notification_button = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int notification_subtitle = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int notification_title = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int notificationbg = 2131296261;
			
			// aapt resource value: 0x7f090010
			public const int share = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int showCustomNotification = 2131296271;
			
			// aapt resource value: 0x7f09000d
			public const int showDialog = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int showStandardNotification = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int switch_cam = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int toggleTheme = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int toggleTitles = 2131296267;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar_custom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int camera_sample = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int content_welcome = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int title_list_item = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int camera_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int main_menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int photo_context_menu = 2131230722;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int app_widget_name = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int camera_sample = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int clip_label = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int notification_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int photo_selection_cab_title = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int widget_empty_view_text = 2131099652;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBar = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ActionBar_Dark = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int ActionBar_Light = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int AppTheme_Dark = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int AppTheme_Light = 2131165187;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AppTheme = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int AppTheme_listDragShadowBackground = 0;
			
			// aapt resource value: 1
			public const int AppTheme_menuIconCamera = 1;
			
			// aapt resource value: 3
			public const int AppTheme_menuIconShare = 3;
			
			// aapt resource value: 2
			public const int AppTheme_menuIconToggle = 2;
			
			private Styleable()
			{
			}
		}
	}
}
