//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWidget
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int star_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int widget_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int widget_bg_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int widget_bg_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int widget_bg_selected = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int bullet = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int definition = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int icon = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int message = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int widget = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int word_title = 2131165187;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int widget_message = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int widget_word = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int widget_loading = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int widget_name = 2131034113;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int BulletPoint = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int Text_Definition = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int Text_Loading = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Text_WordTitle = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Text_WordType = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int WidgetBackground = 2131099648;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int widget_word = 2130968576;
			
			private Xml()
			{
			}
		}
	}
}
