// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Samples.TexturedCube
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_texturedcube = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int f_spot = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pattern = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int translucent = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int hide = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int hidecontainer = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int paintingview = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int show = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int switch_texture = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int hide = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int show = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int switch_texture = 2130968577;
			
			private String()
			{
			}
		}
	}
}
