#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("NotePad.Resource", IsApplication=true)]

namespace NotePad
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int opaque_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int transparent_green = 2130968577;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int large_font_size = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int standard_border = 2131034112;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int body = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int confirm = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int text1 = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int title = 2131230720;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int note_edit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notes_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notes_row = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int body = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int confirm = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int edit_note = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int menu_delete = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int menu_insert = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int no_notes = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int title = 2131099652;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int BaseText = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int SmallText = 2131165185;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
