#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Mono.Samples.SanityTests.Resource", IsApplication=true)]

namespace Mono.Samples.SanityTests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int Description = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int Title = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int Value1 = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int Value2 = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int Value3 = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int StatSample = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] NavBar = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int NavBar_Description = 1;
			
			// aapt resource value: 0
			public const int NavBar_Title = 0;
			
			// aapt resource value: 2
			public const int NavBar_Value1 = 2;
			
			// aapt resource value: 3
			public const int NavBar_Value2 = 3;
			
			// aapt resource value: 4
			public const int NavBar_Value3 = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
