//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int contactEntryText = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int contactList = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int showInvisible = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactEntry = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactManager = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int accountSpinnerLabel = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int addContactButtonLabel = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int addContactTitle = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int allAccounts = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int contactCreationFailure = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int contactEmailLabel = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int contactNameLabel = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int contactPhoneLabel = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int save = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int selectAccountLabel = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int selectLabel = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int showInvisible = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int targetAccountLabel = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int undefinedTypeLabel = 2130968590;
			
			private String()
			{
			}
		}
	}
}
