//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetBoy
{
	
	
	public partial class Resource
	{
		
		public class attr
		{
			
			private attr()
			{
			}
		}
		
		public class drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int asteroid01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int asteroid02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int asteroid03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int asteroid04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int asteroid05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int asteroid06 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int asteroid07 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int asteroid08 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int asteroid09 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int asteroid10 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int asteroid11 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int asteroid12 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int asteroid_explode1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int asteroid_explode2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int asteroid_explode3 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int asteroid_explode4 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int background_a = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int background_b = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int int_timer = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int intbeam_1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int intbeam_2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int intbeam_3 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int intbeam_4 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int laser = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ship2_1 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ship2_2 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ship2_3 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ship2_4 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ship2_hit_1 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ship2_hit_2 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ship2_hit_3 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ship2_hit_4 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int title_bg_hori = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int title_hori = 2130837538;
			
			private drawable()
			{
			}
		}
		
		public class layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			private layout()
			{
			}
		}
		
		public class raw
		{
			
			// aapt resource value: 0x7f040000
			public const int level1 = 2130968576;
			
			private raw()
			{
			}
		}
		
		public class @string
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int start = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int retry = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int restart = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int helpText = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int winText = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int loseText = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int timer = 2131034119;
			
			private @string()
			{
			}
		}
		
		public class style
		{
			
			// aapt resource value: 0x7f060000
			public const int ButtonText = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int helpText = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int timerText = 2131099650;
			
			private style()
			{
			}
		}
		
		public class id
		{
			
			// aapt resource value: 0x7f070000
			public const int JetBoyView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int text = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Button01 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Button02 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int timer = 2131165188;
			
			private id()
			{
			}
		}
	}
}
