#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CardReader.Resource", IsApplication=true)]

namespace CardReader
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int horizontal_page_margin = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int margin_huge = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int margin_large = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int margin_medium = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int margin_small = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int margin_tiny = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int vertical_page_margin = 2131165190;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int card_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tile = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090006
			public const int card_account_field = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int card_account_label = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int card_title = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int log_fragment = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int menu_toggle_log = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int sample_content_fragment = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int sample_main_layout = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int sample_output = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main_fragment = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int account_number = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int card_title = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int intro_message = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int sample_hide_log = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int sample_show_log = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int service_name = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int AppTheme = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Base = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Sample = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Widget = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Widget_SampleMessage = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Widget_SampleMessageTile = 2131099654;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int nfc_tech_filter = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
