#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ActivitySceneTransitionBasic.Resource", IsApplication=true)]

namespace ActivitySceneTransitionBasic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CommonSampleLibrary.Resource.String.library_name = global::ActivitySceneTransitionBasic.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int grid_spacing = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int horizontal_page_margin = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int margin_huge = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int margin_large = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int margin_medium = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int margin_small = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int margin_tiny = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int vertical_page_margin = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int tile = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int grid = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int imageview_header = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int imageview_item = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int textview_name = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int textview_title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int details = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int grid = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int grid_item = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int bacon_ipsum = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int image_header = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int intro_message = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int AppTheme = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Base = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Sample = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int Widget = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Widget_SampleMessage = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Widget_SampleMessageTile = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Transition
		{
			
			// aapt resource value: 0x7f040000
			public const int grid_detail_transition = 2130968576;
			
			static Transition()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Transition()
			{
			}
		}
	}
}
#pragma warning restore 1591
